// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgoxZs8xIstCESIAOQLtxRS4PKzErcSo',
    appId: '1:709422866032:web:a022102b01dafa7ebcdeb5',
    messagingSenderId: '709422866032',
    projectId: 'testev1-85d9b',
    authDomain: 'testev1-85d9b.firebaseapp.com',
    storageBucket: 'testev1-85d9b.firebasestorage.app',
    measurementId: 'G-9G873J1Y91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDr41iUK-crJ90naJHEyeMZWl_7M4DV8',
    appId: '1:709422866032:android:0ad716cb1a7246d6bcdeb5',
    messagingSenderId: '709422866032',
    projectId: 'testev1-85d9b',
    storageBucket: 'testev1-85d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_YOA7g0iZLPWpnNranKkxA1cSA89o5V0',
    appId: '1:709422866032:ios:b6965c9ef9ba4b74bcdeb5',
    messagingSenderId: '709422866032',
    projectId: 'testev1-85d9b',
    storageBucket: 'testev1-85d9b.firebasestorage.app',
    iosBundleId: 'com.example.meuAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_YOA7g0iZLPWpnNranKkxA1cSA89o5V0',
    appId: '1:709422866032:ios:b6965c9ef9ba4b74bcdeb5',
    messagingSenderId: '709422866032',
    projectId: 'testev1-85d9b',
    storageBucket: 'testev1-85d9b.firebasestorage.app',
    iosBundleId: 'com.example.meuAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjgoxZs8xIstCESIAOQLtxRS4PKzErcSo',
    appId: '1:709422866032:web:db6a5e1e746caae9bcdeb5',
    messagingSenderId: '709422866032',
    projectId: 'testev1-85d9b',
    authDomain: 'testev1-85d9b.firebaseapp.com',
    storageBucket: 'testev1-85d9b.firebasestorage.app',
    measurementId: 'G-JJGJ6F0D4D',
  );
}
